### ISSUE TITLE
Behaviour when not specifying namespace

### ISSUE THREAD

**Issue by colinscape** [bufferapp/kubesecret#5]
Version 0.4.0-rc1

I did a `kubesecret get` and forgot to specify the namespace (a common habit I have with `kubectl` too 😅 ).

The output then says `Working with namespace undefined` and it looks like what ends up happening is that the `default` namespace is used.

I'm just wondering if making the namespace required would help to avoid any potential confusion here. Or, at the very least, the informational message could say `Working with namespace default`?

**Comment by djfarrelly** [comment]
Fixed w/ #16
